// <auto-generated />
using System;
using EFPractice.DatabaseAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFPractice.DatabaseAccess.Migrations
{
    [DbContext(typeof(BookLibraryDbContext))]
    [Migration("20260207153435_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors", t =>
                        {
                            t.HasCheckConstraint("CK_Author_BirthDate", "[BirthDate] IS NULL OR [BirthDate] <= CAST(GETDATE() AS DATE)");

                            t.HasCheckConstraint("CK_Author_FirstName", "[FirstName] IS NOT NULL AND LEN(TRIM([FirstName])) > 0");

                            t.HasCheckConstraint("CK_Author_LastName", "[LastName] IS NOT NULL AND LEN(TRIM([LastName])) > 0");
                        });
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.AuthorBiography", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Awards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiographyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique()
                        .HasFilter("[AuthorId] IS NOT NULL");

                    b.ToTable("AuthorBiographies");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Books", t =>
                        {
                            t.HasCheckConstraint("CK_Book_Price", "[Price] IS NULL OR [Price] > 0");

                            t.HasCheckConstraint("CK_Book_PublicationYear", "[PublicationYear] IS NULL OR \r\n                ([PublicationYear] >= 1700 AND [PublicationYear] <= YEAR(GETDATE()))");
                        });
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("date");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.BookDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookDetails", t =>
                        {
                            t.HasCheckConstraint("CK_BookDetail_Edition", "[Edition] > 0");

                            t.HasCheckConstraint("CK_BookDetail_PageCount", "[PageCount] > 0");
                        });
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LoanDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans", t =>
                        {
                            t.HasCheckConstraint("CK_Loan_Dates", "[LoanDate] IS NOT NULL AND \r\n                [DueDate] IS NOT NULL AND\r\n                [LoanDate] <= [DueDate] AND\r\n                [LoanDate] <= CAST(GETDATE() AS DATE) AND\r\n                ([ReturnDate] IS NULL OR [ReturnDate] >= [LoanDate])");
                        });
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Members", t =>
                        {
                            t.HasCheckConstraint("CK_Member_BirthDate", "[BirthDate] IS NULL OR [BirthDate] <= CAST(GETDATE() AS DATE)");

                            t.HasCheckConstraint("CK_Member_FirstName", "[FirstName] IS NOT NULL AND LEN(TRIM([FirstName])) > 0");

                            t.HasCheckConstraint("CK_Member_LastName", "[LastName] IS NOT NULL AND LEN(TRIM([LastName])) > 0");
                        });
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.MemberContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[MemberId] IS NOT NULL");

                    b.ToTable("MemberContacts");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.AuthorBiography", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Author", "Author")
                        .WithOne("AuthorBiography")
                        .HasForeignKey("EFPractice.DatabaseAccess.Models.AuthorBiography", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Book", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EFPractice.DatabaseAccess.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.BookCategory", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFPractice.DatabaseAccess.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.BookDetail", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Book", "Book")
                        .WithOne("BookDetail")
                        .HasForeignKey("EFPractice.DatabaseAccess.Models.BookDetail", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Loan", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFPractice.DatabaseAccess.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.MemberContact", b =>
                {
                    b.HasOne("EFPractice.DatabaseAccess.Models.Member", "Member")
                        .WithOne("MemberContact")
                        .HasForeignKey("EFPractice.DatabaseAccess.Models.MemberContact", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Author", b =>
                {
                    b.Navigation("AuthorBiography");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Book", b =>
                {
                    b.Navigation("BookCategories");

                    b.Navigation("BookDetail");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Member", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("MemberContact");
                });

            modelBuilder.Entity("EFPractice.DatabaseAccess.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
